### PR TITLE
[Addon istio]Modify the label of destinationrules

### PR DESCRIPTION
**Pull request by suwliang3**
Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>

### Description of your changes

modify the destinationrules's label `app.oam.dev/revision` to `service.istio.io/canonical-name`,because the lable `app.oam.dev/revision` belongs to deployment, the pod doesn't have the label.

### How has this code been tested?

following [istio](https://www.bookstack.cn/read/kubevela.io-1.1-zh/3aecdfaa8a4c3bf2.md)

### Checklist

I have:

- [ ] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [ ] Updated/Added any relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [ ] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [ ] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

####  Verified Addon promotion rules

If this pr wants to promote an experimental addon to verified, you must check whether meet these conditions too:
  - [ ] This addon must be tested by addon's [e2e-test](./test/e2e-test/addon-test) to guarantee this addon can be enabled successfully.
  - This addon must have some basic but necessary information.
    - [ ] An accessible icon url and source url defined in addon's `metadata.yaml`.
    - [ ] A detail introduction include a basic example about how to use and what's the benefit of this addon in `README.md`.
    - [ ] Also provide an introduction in KubeVela [documentation](https://kubevela.net/docs/reference/addons/overview).
    - [ ] It's more likely to be accepted if useful examples provided in example [dir](examples/).

### CODE REVIEW

**Comment by wonderflow** [comment]
Can you describe a bit how this label `service.istio.io/canonical-name` works?

**Comment by wonderflow** [comment]
Does it relate with https://github.com/kubevela/kubevela/issues/5148 ?

**Comment by suwliang3** [comment]
> Can you describe a bit how this label `service.istio.io/canonical-name` works?

**Comment by suwliang3** [comment]
> Can you describe a bit how this label `service.istio.io/canonical-name` works?

@wonderflow When a workload is injected into a sidecar, the corresponding  pod will label `service.istio.io/canonical-name`.The lable can be used to  distinguish between different versions in destinationrules.
image

**Comment by suwliang3** [comment]
> Does it relate with [kubevela/kubevela#5148](https://github.com/kubevela/kubevela/issues/5148) ?

yes

**Comment by wonderflow** [comment]
> > Can you describe a bit how this label `service.istio.io/canonical-name` works?
> 
> @wonderflow When a workload is injected into a sidecar, the corresponding pod will label `service.istio.io/canonical-name`.The lable can be used to distinguish between different versions in destinationrules. image

Does the inject automatically done by istio?

**Comment by suwliang3** [comment]
> 

yes

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
