### PR TITLE
[Addon] Feat - bump deps flux

### PR DESCRIPTION
**Pull request by s4rd1nh4**
### Description of your changes
feat - bump deps flux

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [x] Updated/Added any relevant [documentation] and [examples].
- [x] Unit/E2E Tests added.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
what's difference?

**Comment by s4rd1nh4** [comment]
> what's difference?
https://github.com/fluxcd/helm-controller/blob/main/CHANGELOG.md#0220

> kube: load KubeConfig (token) from FS on every reconcile https://github.com/fluxcd/helm-controller/pull/480

**Review by wonderflow — APPROVED** [review]
Thanks

**Review by wangyikewxgm — APPROVED** [review]
Thanks

**Pull request merged**
