### PR TITLE
[Addon] Feat: adjust fluxcd kustomize, support for more native fields

### PR DESCRIPTION
**Pull request by zxbyoyoyo**
### Description of your changes

Fixes # adjust fluxcd kustomize, support for more native fields

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [ ] Updated/Added any relevant [documentation] and [examples].
- [ ] Unit/E2E Tests added.

### CODE REVIEW

**Comment by wonderflow** [comment]
Can you clarify the scenario

**Comment by zxbyoyoyo** [comment]
> Can you clarify the scenario

We use fluxcd to implement GitOps. The native fluxcd kustomize supports the following features:
1. determine whether to enable garbage collection by setting `spec.prune`. When the kustomize component is deleted or a Git resource is deleted, the resources in k8s are automatically deleted; although this field is a bit ambiguous, see issue: https://github. com/fluxcd/kustomize-controller/issues/662
2. determine whether to suspend pulling Git updates by setting `spec.suspend`;
3. determine whether to force the update by setting `spec.force`. When a Git resource has a problem and cannot be applied, other resources can be applied normally.

when I use Kubevela kustomize componet to create a fluxcd instance, (gitrepository, kustomize) objects are automatically created, but there is no entry for setting these parameters.

**Comment by wonderflow** [comment]
ok, that's fine for me, do we need to update the version? \cc @wangyikewxgm

**Comment by wonderflow** [comment]
maybe we can merge it with #365

**Comment by wangyikewxgm** [comment]
generally ok, please rebase with master and modify metadata upgrade the addon version

**Review by diego-milhomes — APPROVED** [review]
lgtm

**Review by wonderflow — APPROVED** [review]

**Review by FogDong — APPROVED** [review]

**Pull request merged**
