### PR TITLE
[Addon] Add Crossplane Azure Addon for provisioning Cloud Resources on Azure

### PR DESCRIPTION
**Pull request by yogeshselvarajan**
### Title
[Addon] Add Crossplane-Azure Addon

### Description of your changes

This PR adds the **Crossplane-Azure** addon to the KubeVela catalog as an experimental addon. The addon facilitates the provisioning of Azure resources like Resource Groups, Virtual Networks, and Storage Accounts via Crossplane on KubeVela.

- It contains necessary components, including CUE files and provider configurations, as well as a detailed `README.md` file explaining the usage, installation, and authentication setup. 
- Additionally, examples are provided in the `examples` directory, showing the Azure Resource Group, Virtual Network, and Storage Account creation.

### How has this code been tested?

I have copied the entire addon directory `crossplane-azure`, which contains the CUE files and provider files. I tested this locally by using the following command:

```bash
vela addon enable ./<the-directory-path>
```
After enabling the addon, I verified the resource provisioning in my Azure portal. The expected resources (Resource Group, Virtual Network, and Storage Account) were successfully created. 

### Checklist

I have:

- [✔] Title of the PR starts with type (e.g. `[Addon]`, `[example]`, or `[Doc]`).
- [✔] Updated/Added relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [✔] Placed the new addon in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [✔] Updated the addon version in `metadata.yaml`.

### Request for Reviewers

Dear Maintainers,

This PR introduces the **Crossplane-Azure** addon for provisioning Azure resources (Resource Groups, VNETs, Storage Accounts) via Crossplane in KubeVela. I kindly request that this addon (Crossplane-Azure), along with the **[Crossplane](https://github.com/kubevela/catalog/tree/master/experimental/addons/crossplane)** and **[Crossplane-AWS](https://github.com/kubevela/catalog/tree/master/experimental/addons/crossplane-aws)** addons (currently in experimental), be promoted to public. This would enable users to manage cloud resources more efficiently across Azure and AWS using Kubevela.

**In future updates, I plan to add more CUE files for Azure resources to expand its provisioning capabilities from KubeVela. I will include the proper CUE files using the Azure CRDs for Crossplane (refering [Azure CRDs for Crossplane](https://doc.crds.dev/github.com/crossplane/provider-azure)).**

### CODE REVIEW

**Comment by anoop2811** [comment]
Can you make sure your commits are signed?

**Comment by yogeshselvarajan** [comment]
> Can you make sure your commits are signed?

@anoop2811 Yes, I have followed the steps and signed the commit. I have force-pushed the commit again with signing using the following commands:

```bash
git rebase HEAD~1 --signoff
git push --force-with-lease origin crossplane-azure-addon
```

**Review by anoop2811 — APPROVED** [review]

**Comment by anoop2811** [comment]
Thank you for your contrinution @yogeshselvarajan !

**Comment by yogeshselvarajan** [comment]
Also @anoop2811, I see that the PR has been merged, but I noticed that my new addon isn't reflecting in the KubeVela UI. I can only see the existing Crossplane and Crossplane-AWS addons (attached screenshot), with the expeiremntal addon source too enabled in the KubeVela. 

Should I be updating something like an OSS bucket, or is there a need to modify the invisible tag in the addon file? Please advise on what might be missing.

**Pull request merged**
