### PR TITLE
Addon Postgrest

### PR DESCRIPTION
**Pull request by MdSahil-oss**
### Description of your changes
This PR Adds Postgrest as an addon

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [x] Updated/Added any relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [x] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [x] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

####  Verified Addon promotion rules

If this pr wants to promote an experimental addon to verified, you must check whether meet these conditions too:
  - [x] This addon must be tested by addon's [e2e-test](./test/e2e-test/addon-test) to guarantee this addon can be enabled successfully.
  - This addon must have some basic but necessary information.
    - [x] An accessible icon url and source url defined in addon's `metadata.yaml`.
    - [x] A detail introduction include a basic example about how to use and what's the benefit of this addon in `README.md`.
    - [ ] Also provide an introduction in KubeVela [documentation](https://kubevela.net/docs/reference/addons/overview).
    - [ ] It's more likely to be accepted if useful examples provided in example [dir](examples/).

### CODE REVIEW

**Comment by wangyikewxgm** [comment]
Although we already have the Postgrest operator as an addon, there are potential reasons to consider the need for this new one?

**Comment by MdSahil-oss** [comment]
@wangyikewxgm Yes, We do have `Postgres-Operator` as addon but don't have `Postgrest` as addon for more please visit https://postgrest.org/en/stable/

**Comment by wangyikewxgm** [comment]
> @wangyikewxgm Yes, We do have `Postgres-Operator` as addon but don't have `Postgrest` as addon for more please visit https://postgrest.org/en/stable/

Can we use this component [Definition](https://github.com/kubevela/catalog/blob/master/experimental/addons/postgres-operator/definitions/postgres-cluster.cue) to create  a postgrest database instance?

**Comment by MdSahil-oss** [comment]
@wangyikewxgm I think it will not be possible, as creating a working `postgrest` instance requires setting parameter `PGRST_DB_URI` to connect `postgrest` with running `postres` successfully and the postgre-operator's [component definition](https://github.com/kubevela/catalog/blob/master/experimental/addons/postgres-operator/definitions/postgres-cluster.cue) is used to create an instance for postgres.

I hope it makes sence to you.

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
