### PR TITLE
[Addon] add terraform-vsphere addon

### PR DESCRIPTION
**Pull request by lunarwhite**
### Description of your changes

Fixes: https://github.com/kubevela/kubevela/issues/3337

Per this guide: https://kubevela.io/docs/platform-engineers/addon/terraform

I've done:

* prepare metadata for the VMware vSphere, per [kubevela/terraform-controller](https://github.com/kubevela/terraform-controller/blob/master/controllers/provider/vsphere.go).
* generate the Terraform addon by `make terraform-addon-gen`.
* verify the addon in local velad env.

### How has this code been tested?

Try to enable the addon by local dir in local velad env, and check the created provider. 

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [x] Updated/Added any relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [ ] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [ ] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

**Note**

I'm not sure if this is considered a "new" addon, since it is a terraform addon and automatically generated in dir `./addon`. So I just keep it in the origin path. If not proper, we can move it into `./experimental/addons`.

### CODE REVIEW

**Comment by chivalryq** [comment]
Can you provide at least one component definition in the addon and test if provider works?

**Comment by chivalryq** [comment]
Is this PR still in progress? @lunarwhite

**Comment by lunarwhite** [comment]
Yes, still WIP. vSphere is not a public cloud provider like aws/gcp, so it would take more efforts to setup the platform from scratch. BTW, Are you familiar with setuping vSphere?

I would update if met trouble.

**Comment by chivalryq** [comment]
I didn't use vSphere. But if you met trouble, free to ask here.

**Comment by lunarwhite** [comment]
I've add two component definitions for addon `terraform-vsphere`
- https://github.com/kubevela-contrib/terraform-modules/pull/16
- https://github.com/kubevela-contrib/terraform-modules/pull/17

Next step, I'll add related docs in kubevela.io.

**Comment by chivalryq** [comment]
After checking the vShpere terraform provider and vSphere file resources. I'm not sure how this vSphere provider can do with KubeVela. 

Let's say you create application with a vsphere_file component. That means user upload a file to vSphere datastore? When the application is deleted, will the file uploaded be deleted in vSphere datastore? In what situation will user create an application to upload a file?

On the other hand, user have to create vsphere datastore in the vSphere portal by hand. We should provide a complete use case.

**Comment by lunarwhite** [comment]
> After checking the vShpere terraform provider and vSphere file resources. I'm not sure how this vSphere provider can do with KubeVela.

As a non public cloud provider, vSphere requires user to setup [vCenter Server](https://www.vmware.com/products/vcenter-server.html) and [ESXi](https://www.vmware.com/products/esxi-and-esx.html). Refere to the [provider docs](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs) for info on all of the resources and data sources supported by this provider. Each includes a detailed description of the purpose and how to use it.

> Let's say you create application with a vsphere_file component. That means user upload a file to vSphere datastore? 

Right. User also can copy files between datastores, or from one location to another on the same datastore.

> When the application is deleted, will the file uploaded be deleted in vSphere datastore? 

Yes. It's like `terraform apply` and `terraform destroy`.

> In what situation will user create an application to upload a file?

In vSphere design, `file` here means ISOs and virtual disk files in most cases.

> On the other hand, user have to create vsphere datastore in the vSphere portal by hand. We should provide a complete use case.

Yes, user should have a datastore resource to use `vsphere_file`. I choose those two just for quickly verifying the addon. Maybe We could add more supported resources in the future.

**Review by chivalryq — APPROVED** [review]
Sorry for the late reply. Good job! LGTM

**Comment by lunarwhite** [comment]
Hi @chivalryq @wangyikewxgm , thanks for your reviews! I've move it to `experimental/addon`

**Review by wangyikewxgm — APPROVED** [review]

**Pull request merged**
