### PR TITLE
Feat: Extract the view files used by VelaUX addon into a separate folder for deployment

### PR DESCRIPTION
**Pull request by Hanmengnan**
Extract the view files used by VelaUX addon into a separate folder for deployment.

Kubevela has supported the new directory structure. For details, see https://github.com/kubevela/kubevela/pull/4154.

The addon directory structure is:

```shell
├── resources/
├── definitions/
├── schemas/
├── views/
│   ├── pod-view.cue
│   └── component-pod-view.cue
├── README.md
├── metadata.yaml
└── template.yaml
```

Signed-off-by: HanMengnan <1448189829@qq.com>

### Checklist

I have:

- [ ] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [ ] Updated/Added any relevant [documentation] and [examples].
- [ ] Unit/E2E Tests added.

### CODE REVIEW

**Comment by wonderflow** [comment]
This PR depends the v1.5 release of kubevela, and we should wait for this feature: https://github.com/kubevela/kubevela/issues/4181

**Comment by yangsoon** [comment]
good job!

**Comment by barnettZQG** [comment]
@Hanmengnan Please change the VelaUX addon version to v1.5.0-alpha.2

**Comment by barnettZQG** [comment]
Refer to #398

**Pull request closed without merging**
