### PR TITLE
Fix: removes parameter name for terraform cloud-provider

### PR DESCRIPTION
**Pull request by afzalbin64**
### Description of your changes

For[ #5468](https://github.com/kubevela/kubevela/pull/5468)

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [x] Updated/Added any relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [ ] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [x] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

####  Verified Addon promotion rules

If this pr wants to promote an experimental addon to verified, you must check whether meet these conditions too:
  - [ ] This addon must be tested by addon's [e2e-test](./test/e2e-test/addon-test) to guarantee this addon can be enabled successfully.
  - This addon must have some basic but necessary information.
    - [ ] An accessible icon url and source url defined in addon's `metadata.yaml`.
    - [ ] A detail introduction include a basic example about how to use and what's the benefit of this addon in `README.md`.
    - [ ] Also provide an introduction in KubeVela [documentation](https://kubevela.net/docs/reference/addons/overview).
    - [ ] It's more likely to be accepted if useful examples provided in example [dir](examples/).

### CODE REVIEW

**Comment by chivalryq** [comment]
Please do this to all other provider. Also promote the version of addons.

**Comment by charlie0129** [comment]
The addon version should be bumped instead, not dependency version

https://github.com/kubevela/catalog/blob/f1a99ceb9106af017500173e8ed63e957b1dbe3d/addons/terraform-alibaba/metadata.yaml#L2

**Comment by afzalbin64** [comment]
Ah, I see. It looks like I did oversee that. Thanks for that. For that, we need to figure out like Alibaba Cloud `1.198.0`. Thoughts?

**Comment by wonderflow** [comment]
It's really confusing that all different terraform providers share the same default name called "default". The default name shouldn't be `default`. @chivalryq

**Comment by charlie0129** [comment]
> Ah, I see. It looks like I did oversee that. Thanks for that. For that, we need to figure out like Alibaba Cloud `1.198.0`. Thoughts?

We only need to decide the version of addons in this repo. As of MAJOR.MINOR.PATCH (in this example, `1.0.5`) semantic versioning, you can try to bump either MINOR or PATCH version. Something like `1.0.6` will do.

**Comment by chivalryq** [comment]
@wonderflow Yes, I re-provision all resources one time before. And I realized that it's dangerous to have a default name of Provider in config management. It makes user to implicitly override the default Provider.
That's why I propose to remove the default name.

**Review by chivalryq — APPROVED** [review]

**Comment by chivalryq** [comment]
ping @wangyikewxgm

**Review by wangyikewxgm — APPROVED** [review]

**Pull request merged**
