### PR TITLE
[Addon] Fix the version issue of flink-kubernetes-operator

### PR DESCRIPTION
**Pull request by yanghua**
### Description of your changes

changed the version from 1.1.0 to 1.3.0

### How has this code been tested?

debugged the addon in my local, installed offline:

```
vela addon enable /root/.vela/addons/flink-kubernetes-operator
```

show the status:
```
vela addon status flink-kubernetes-operator
```

the result：

```
flink-kubernetes-operator: enabled (1.3.0)
==> Installed Clusters
[local]
==> Registry Name
local
```

### Checklist

I have:

- [ ] Title of the PR starts with type (e.g. `[Addon]` , `[example]` or `[Doc]`).
- [ ] Updated/Added any relevant [documentation](https://kubevela.io/docs/reference/addons/overview) and [examples](https://github.com/kubevela/catalog/tree/master/examples).
- [ ] New addon should be put in [experimental](https://github.com/kubevela/catalog/tree/master/experimental/addons).
- [ ] Update addon should modify the `version` in `metadata.yaml` to generate a new version.

####  Verified Addon promotion rules

If this pr wants to promote an experimental addon to verified, you must check whether meet these conditions too:
  - [ ] This addon must be tested by addon's [e2e-test](./test/e2e-test/addon-test) to guarantee this addon can be enabled successfully.
  - This addon must have some basic but necessary information.
    - [ ] An accessible icon url and source url defined in addon's `metadata.yaml`.
    - [ ] A detail introduction include a basic example about how to use and what's the benefit of this addon in `README.md`.
    - [ ] Also provide an introduction in KubeVela [documentation](https://kubevela.net/docs/reference/addons/overview).
    - [ ] It's more likely to be accepted if useful examples provided in example [dir](examples/).

### CODE REVIEW

**Comment by wangyikewxgm** [comment]
Thanks for contribution, please sign the DCO.

**Comment by yanghua** [comment]
> Thanks for contribution, please sign the DCO.

@wangyikewxgm thanks for the reminder, signed.

**Comment by wangyikewxgm** [comment]
Previously, due to this error, we pended the test for flink addon pre : https://github.com/kubevela/catalog/blob/55cf6be3c4195093ea9ba87c69a9c004baceee07/test/e2e-test/addon-test/PENDING#L6. Can you remove it from this file to let CI workflow test it?

**Review by wangyikewxgm — APPROVED** [review]
Good job! Thanks for your first commit.

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
