### PR TITLE
[Addon] Upgrade Flux Addon

### PR DESCRIPTION
**Pull request by s4rd1nh4**
Signed-off-by: s4rd1nh4 <diego.milhomes@gmail.com>

### Description of your changes
Upgrade Flux addon to address the recent vulnerabilities.
https://fluxcd.io/blog/2022/05/may-2022-security-announcement/

### How has this code been tested?
v1beta2 API is backward compatible with v1beta1 - https://github.com/fluxcd/flux2/discussions/2567

### Checklist

I have:

- [x] Title of the PR starts with type (e.g. `[Addon]` or `[Trait]`).
- [x] Updated/Added any relevant [documentation] and [examples].
- [ ] Unit/E2E Tests added.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
Thanks @s4rd1nh4 

Recently, we're reported the affect of EKS 1.21, will this PR related with this?

> Hi team, with the recent [announcement](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21) made for EKS 1.21, service account token will now have an expiration of one hour. We found that flux-system:sa-helm-controller is one of the affected deployments. Is there any fix for this issue or any upcoming plan for the same?

**Review by wonderflow — APPROVED** [review]
LGTM. ping @wangyikewxgm

**Comment by s4rd1nh4** [comment]
> Thanks @s4rd1nh4
> 
> Recently, we're reported the affect of EKS 1.21, will this PR related with this?
> 
> > Hi team, with the recent [announcement](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21) made for EKS 1.21, service account token will now have an expiration of one hour. We found that flux-system:sa-helm-controller is one of the affected deployments. Is there any fix for this issue or any upcoming plan for the same?

indirectly yes, because in current versions flux already uses the k8s sdk versions that implement refresh tokens automatically within the required time frame

**Comment by wonderflow** [comment]
@s4rd1nh4 great

**Review by FogDong — APPROVED** [review]

**Comment by s4rd1nh4** [comment]
> @s4rd1nh4 great

https://github.com/fluxcd/helm-controller/pull/480

**Review by wangyikewxgm — APPROVED** [review]
Good Job!

**Pull request merged**
